# Generated by Django 3.1 on 2021-05-03 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceID', models.IntegerField(default=0)),
                ('childID', models.IntegerField(default=0)),
                ('firstName', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('rate', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('OS', 'outstanding'), ('PD', 'paid')], default='OS', max_length=20)),
                ('year', models.IntegerField(choices=[(2021, 2021), (2022, 2022)], default=2021)),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='January', max_length=10)),
                ('week1', models.CharField(max_length=64)),
                ('week2', models.CharField(max_length=64)),
                ('week3', models.CharField(max_length=64)),
                ('week4', models.CharField(max_length=64)),
                ('week1Hours', models.IntegerField(default=0)),
                ('week2Hours', models.IntegerField(default=0)),
                ('week3Hours', models.IntegerField(default=0)),
                ('week4Hours', models.IntegerField(default=0)),
                ('week1mins', models.IntegerField(default=0)),
                ('week2mins', models.IntegerField(default=0)),
                ('week3mins', models.IntegerField(default=0)),
                ('week4mins', models.IntegerField(default=0)),
                ('week1Rate', models.CharField(default='Full Time', max_length=20)),
                ('week2Rate', models.CharField(default='Full Time', max_length=20)),
                ('week3Rate', models.CharField(default='Full Time', max_length=20)),
                ('week4Rate', models.CharField(default='Full Time', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullday', models.IntegerField()),
                ('halfday', models.IntegerField()),
                ('parttime', models.IntegerField()),
                ('afterschool', models.IntegerField()),
                ('latepayment', models.IntegerField()),
                ('retainer', models.IntegerField()),
                ('saturdaycreche', models.IntegerField()),
                ('eveningcare', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=64)),
                ('amount', models.CharField(max_length=64)),
                ('purchase', models.CharField(max_length=64)),
            ],
        ),
    ]
