# Generated by Django 3.1 on 2021-05-03 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_invoice_invoiceid'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='parentName',
            field=models.CharField(default='not selected', max_length=64),
            preserve_default=False,
        ),
    ]
