# Generated by Django 3.1 on 2021-05-06 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210506_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='kids',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
