# Generated by Django 3.1 on 2021-05-07 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_invoice_kids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='kids',
            new_name='children',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='week1Rate',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='week2Rate',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='week3Rate',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='week4Rate',
        ),
        migrations.AddField(
            model_name='invoice',
            name='sub',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='rate',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='week1',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='week1Hours',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='week1mins',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='week2',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='week2Hours',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='week2mins',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='week3',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='week3Hours',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='week3mins',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='week4',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='week4Hours',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='week4mins',
            field=models.CharField(default='', max_length=64),
        ),
    ]
