# Generated by Django 3.1 on 2021-05-11 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210508_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='latepayment',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='latepickup',
            field=models.IntegerField(default=0.0),
        ),
    ]
