# Generated by Django 3.1 on 2021-09-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_invoice_parentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='week5',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='invoice',
            name='week5Hours',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='invoice',
            name='week5mins',
            field=models.CharField(default='', max_length=64),
        ),
    ]
