# Generated by Django 3.1 on 2021-09-04 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210904_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='period',
            field=models.CharField(default='', max_length=64),
        ),
    ]
