# Generated by Django 3.1 on 2021-09-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210905_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricing',
            old_name='retainer',
            new_name='fulldayretainer',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='afterschool',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='halfday',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='saturdaycreche',
        ),
        migrations.AddField(
            model_name='pricing',
            name='parttimeretainer',
            field=models.IntegerField(default=0),
        ),
    ]
