# Generated by Django 3.1 on 2021-09-07 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210906_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='sub',
        ),
    ]
