# Generated by Django 3.1 on 2021-09-07 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_invoice_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='latepickup',
            field=models.IntegerField(default=0),
        ),
    ]
