# Generated by Django 3.1 on 2021-09-08 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_pricing_latepickup'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='reason',
            field=models.CharField(default='', max_length=64),
        ),
    ]
