# Generated by Django 2.2.1 on 2020-05-19 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creche', '0002_auto_20200519_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidays',
            name='holiday',
            field=models.CharField(default='no selection', max_length=20),
            preserve_default=False,
        ),
    ]
