# Generated by Django 2.2.1 on 2020-05-19 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creche', '0004_remove_holidays_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidays',
            name='holiday',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
