# Generated by Django 3.1 on 2020-09-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creche', '0005_holidays_holiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('surname', models.CharField(max_length=20)),
                ('firstname', models.CharField(max_length=20)),
            ],
        ),
    ]
