# Generated by Django 3.1 on 2021-08-27 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mondaystart', models.TimeField(default='00:00')),
                ('mondayfinish', models.TimeField(default='00:00')),
                ('tuesdaystart', models.TimeField(default='00:00')),
                ('tuesdayfinish', models.TimeField(default='00:00')),
                ('wednesdaystart', models.TimeField(default='00:00')),
                ('wednesdayfinish', models.TimeField(default='00:00')),
                ('thursdaystart', models.TimeField(default='00:00')),
                ('thursdayfinish', models.TimeField(default='00:00')),
                ('fridaystart', models.TimeField(default='00:00')),
                ('fridayfinish', models.TimeField(default='00:00')),
                ('saturdaystart', models.TimeField(default='00:00')),
                ('saturdayfinish', models.TimeField(default='00:00')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=20)),
                ('firstname', models.CharField(max_length=20)),
                ('relation', models.CharField(max_length=20)),
                ('mainNumber', models.CharField(max_length=11)),
                ('altNumber', models.CharField(max_length=11)),
                ('otherNumber', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'Parent',
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=64)),
                ('firstname', models.CharField(max_length=64)),
                ('dateofbirth', models.DateField()),
                ('childgender', models.CharField(max_length=10)),
                ('childtype', models.CharField(max_length=64)),
                ('maincontact', models.CharField(max_length=64)),
                ('c1', models.CharField(max_length=11)),
                ('c2', models.CharField(max_length=11)),
                ('othercontact', models.CharField(max_length=64)),
                ('c3', models.CharField(max_length=11)),
                ('childphoto', models.ImageField(default='images/no_boy_photo.png', upload_to='images/')),
                ('active', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=1024)),
                ('medical', models.CharField(max_length=100)),
                ('dietry', models.CharField(max_length=100)),
                ('mondaystart', models.TimeField(default='00:00')),
                ('mondayfinish', models.TimeField(default='00:00')),
                ('tuesdaystart', models.TimeField(default='00:00')),
                ('tuesdayfinish', models.TimeField(default='00:00')),
                ('wednesdaystart', models.TimeField(default='00:00')),
                ('wednesdayfinish', models.TimeField(default='00:00')),
                ('thursdaystart', models.TimeField(default='00:00')),
                ('thursdayfinish', models.TimeField(default='00:00')),
                ('fridaystart', models.TimeField(default='00:00')),
                ('fridayfinish', models.TimeField(default='00:00')),
                ('saturdaystart', models.TimeField(default='00:00')),
                ('saturdayfinish', models.TimeField(default='00:00')),
                ('totalHours', models.IntegerField(default=0)),
                ('totalMins', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='child.parent')),
            ],
        ),
    ]
