# Generated by Django 3.1 on 2021-09-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0002_auto_20210828_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='daysperweek',
            field=models.IntegerField(default=0),
        ),
    ]
