# Generated by Django 3.1 on 2021-09-06 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0004_child_dayspermonth'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='childtypefee',
            field=models.IntegerField(default=0),
        ),
    ]
